# This is a basic workflow to help you get started with Actions

name: iac_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    paths:
    - "iac/bicep/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_ID: "0.0"
  LOCATION: "westus"
  RESOURCES_PREFIX: "devopsohteam10614"
  WORKDIR: "iac/bicep/"
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  
jobs:
#   bicep-linter:
#       name: Bicep Linter
#       runs-on: ubuntu-latest
#       steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: '0'
#       - name: Run Bicep Linter
#         uses: synergy-au/bicep-lint-action@v1
#         with:
#           analyse-all-files: 'true'

    # Steps represent a sequence of tasks that will be executed as part of the job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: "production"
     
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get repo name
      uses: actions/github-script@v5
      id: resources_prefix
      with:
        result-encoding: string
        script: return context.repo.repo.toLowerCase()
        
    - name: preview
      uses: azure/CLI@v1
      with:
          azcliversion: 2.30.0
          inlineScript: |
                az deployment sub what-if --name "${RESOURCES_PREFIX}-${BUILD_ID}" --template-file ${{ env.WORKDIR }}/main.bicep --location "${{ secrets.LOCATION }}" --parameters resourcesPrefix=${{ steps.resources_prefix.outputs.result }}
      
    - name: Deploy
      uses: azure/CLI@v1
      with:
          azcliversion: 2.30.0
          inlineScript: |
                az deployment sub create --name "${RESOURCES_PREFIX}-${BUILD_ID}" --template-file ${{ env.WORKDIR }}/main.bicep --location "${{ secrets.LOCATION }}" --parameters resourcesPrefix=${{ steps.resources_prefix.outputs.result }}
      
      
        
  
  
